# Generated by Django 3.1 on 2022-03-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
