# Generated by Django 3.1 on 2022-02-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='carts',
            new_name='cart',
        ),
    ]
